"""Migration 3

Revision ID: 90c2a28471ec
Revises: 69751050c01d
Create Date: 2024-11-06 12:58:22.524048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c2a28471ec'
down_revision: Union[str, None] = '69751050c01d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pavan')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pavan', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
